function labels = importlabel(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  LABELS = IMPORTFILE1(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the numeric data.
%
%  LABELS = IMPORTFILE1(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  labels = importfile1("C:\Users\Nobody\Desktop\ATD\Projeto\labels.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 13-May-2020 13:13:58

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Import the data
labels = readtable(filename, opts);

%% Convert to output type
labels = table2array(labels);
end